CREATE ROLE demo WITH LOGIN NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION ENCRYPTED PASSWORD 'demo';
REVOKE ALL on DATABASE postgres from demo;
CREATE DATABASE demo WITH OWNER = demo ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;
